version: '3.3'

services:
  mysql-server:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_database
      - mysql_user
      - mysql_password
      - mysql_root_password
    ports:
      - "13306:3306"
    command: --character-set-server=utf8 --collation-server=utf8_bin

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:centos-4.4.4
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_database
      - mysql_user
      - mysql_password
      - mysql_root_password
    ports:
      - "10051:10051"

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:centos-4.4.4
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      PHP_TZ: "Asia/Singapore"
    secrets:
      - mysql_database
      - mysql_user
      - mysql_password
      - mysql_root_password
    ports:
      - "18080:80"

secrets:
  mysql_database:
    external: true
  mysql_user:
    external: true
  mysql_password:
    external: true
  mysql_root_password:
    external: true

